apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    app: model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: tresvitae/house-price-model:latest
        imagePullPolicy: Never  # Use local image since we built it locally
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONPATH
          value: "/app"
---
apiVersion: v1
kind: Service
metadata:
  name: model
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30100
  selector:
    app: model
