apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: tresvitae/streamlit:latest
        imagePullPolicy: Never  # Use local image since we built it locally
        ports:
        - containerPort: 8501
        env:
        - name: MODEL_API_URL
          value: "http://model:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30000
  selector:
    app: streamlit
